### ISSUE TITLE
Installing packages without sufficient checks

### ISSUE THREAD

**Issue by Vishnuparammal** [SRA-VJTI/MARIO#2]
The install_codes.sh has a version specific (kinetic) command without proper check  [ros-kinetic-rosserial](https://github.com/SRA-VJTI/ROS-Workshop-2.1/blob/421385332b833aa6e2deba377620c4152f8a4ee7/install_codes.sh#L11)
It would be better if you can simply display the install command and quit.
`sudo apt install ros-<version>-rosserial`
This will avoid breaking of script in the future, and allow melodic+ users to setup the environment without hassle

**Comment by VedantParanjape** [comment]
I can automate this, i.e. check version of installed ros package and accordingly install the rosserial package.

Is it okay if I implement it this way?
