### ISSUE TITLE
Changing the gripper design

### ISSUE THREAD

**Issue by ChinmayMundane** [SRA-VJTI/MARIO#27]
The aim of this issue is to design a new gripper for MARIO.
Older version of MARIO manipulator had an issue with its gripping mechanism. This time, we are thinking of designing new gripper for this purpose. 
Currently, There are two designs that we have thought of :

1. Gripper using rack and pinion mechanism : 
In this mechanism, gripping is done using rack and pinion structure which is supported/actuated by gear linked with motor.
![Screenshot (58)](https://user-images.githubusercontent.com/109454803/228239458-18e82f90-ac90-468e-add8-640530ff3964.png)

2.  Gripper using more support
This design is similar to the previous one except it has more support which allows it to rotate in a proper manner.

![Screenshot (59)](https://user-images.githubusercontent.com/109454803/228239466-ad321148-7e3e-488d-97cf-c948b1e6704a.png)

**Comment by aPR0T0** [comment]
I Think first design is pretty crude so let's first make it feasible first and my suggestion would pe get the hardware in hand of both and then compare which will be better

**Comment by Jamm02** [comment]
> 2. Gripper using more support
>    This design is similar to the previous one except it has more support which allows it to rotate in a proper manner.
> 
> ![Screenshot (59)](https://user-images.githubusercontent.com/109454803/228239466-ad321148-7e3e-488d-97cf-c948b1e6704a.png)

This design is not economical, keeping the costs in mind the designs should include minimum number of parts.

**Comment by marck3131** [comment]
The older version had issues with the loose end / the driven gear, you can redesign the same with additional support. 
The 1st one can only grab objects perpendicular / and as Alqama already mentioned that the sliding length is too short to grasp other objects.
For the 2nd one, not mainly the gripper will cost more, but because of such design , you might have to redesign the other joints too, which would then be cost effective altogether, but you can go ahead by making a few changes and having a prototype in hand and test.

**Comment by aPR0T0** [comment]
> This design is not economical, keeping the costs in mind the designs should include minimum number of parts.

@Jamm02 I don't think cost will be very high for this design, it has small links so should be feasible

**Comment by Jamm02** [comment]
> > This design is not economical, keeping the costs in mind the designs should include minimum number of parts.
> 
> @Jamm02 I don't think cost will be very high for this design, it has small links so should be feasible

Make a prototype and provide a cost breakdown for the same. 
Be ready with atleast two bot prototypes by 10th April.

**Comment by ChinmayMundane** [comment]
https://user-images.githubusercontent.com/109454803/233845934-c9d04851-fe0d-416c-b893-c2478196c231.mp4

The issue has been resolved.
